In [1]:
from sklearn.linear_model import Perceptron

# 훈련 집합 구축
X=[[0,0],[0,1],[1,0],[1,1]]
y=[-1,1,1,1]

# fit 함수로 Perceptron 학습
p=Perceptron()
p.fit(X,y)

print("학습된 퍼셉트론의 매개변수: ",p.coef_,p.intercept_)
print("훈련집합에 대한 예측: ",p.predict(X))
print("정확률 측정: ",p.score(X,y)*100,"%")

학습된 퍼셉트론의 매개변수:  [[2. 2.]] [-1.]
훈련집합에 대한 예측:  [-1  1  1  1]
정확률 측정:  100.0 %


In [2]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.6)

# fit 함수로 Perceptron 학습
p=Perceptron(max_iter=100,eta0=0.001,verbose=0)
p.fit(x_train,y_train) # digit 데이터로 모델링
res=p.predict(x_test) # 테스트 집합으로 예측
# print(res)
# print(y_test)
# 혼동 행렬
conf=np.zeros((10,10))
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)
# 정확률 계산
no_correct=0
for i in range(10):
    no_correct+=conf[i][i]
accuracy=no_correct/len(res)
print("테스트 집합에 대한 정확률은 ", accuracy*100, "%입니다.")

[[59.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0. 59.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  1. 66.  3.  0.  0.  0.  0.  4.  0.]
 [ 0.  0.  0. 71.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. 75.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  2.  0. 71.  1.  0.  0.  1.]
 [ 2.  2.  0.  0.  1.  1. 77.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  0. 77.  0.  0.]
 [ 0.  2.  0.  0.  1.  0.  0.  0. 52.  4.]
 [ 0.  2.  0.  2.  0.  1.  0.  3.  0. 71.]]
테스트 집합에 대한 정확률은  94.29763560500696 %입니다.
